services:
  shell:
    build:
      context: .
      dockerfile: ui/shell/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - login
      - todos

  login:
    build:
      context: .
      dockerfile: ui/login/Dockerfile
    ports:
      - '4201:4201'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  todos:
    build:
      context: .
      dockerfile: ui/todos/Dockerfile
    ports:
      - '4202:4202'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # todos-api:
  #   build:
  #     context: .
  #     dockerfile: backend/todos-api/Dockerfile
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

  # auth-api:
  #   build:
  #     context: .
  #     dockerfile: backend/auth-api/Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=strongpassword
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
